query menu($mobile: Boolean)
        {
            menu {
                id
                displayName
                items {
                    id
                    to
                    displayName
                }
            }
        }

