import {
  Address,
  Country,
  Organization,
  SalesInvoiceVat,
  SalesInvoice,
  Currency,
  AccountingScheme,
  Customer,
  Bank,
  BankAccount,
  CurrencyRate,
  DocumentNumberSequence,
  Tax,
  SalesInvoiceLine,
  Product, User, UserToOrganization, UserIdentity
} from './entity.base';

export const entities = [
  Address,
  Country,
  Organization,
  SalesInvoiceVat,
  SalesInvoice,
  Currency,
  AccountingScheme,
  Customer,
  Bank,
  BankAccount,
  CurrencyRate,
  DocumentNumberSequence,
  Tax,
  SalesInvoiceLine,
  Product,
  User,
  UserToOrganization,
  UserIdentity,
];
