fragment AccountingSchemeDetailParts on AccountingScheme {
    id
    displayName
    currency {
        isoCode
    }
}

fragment AccountingSchemeListParts on AccountingScheme {
    id
    displayName
    currency {
        isoCode
    }
}
