fragment AccountingSchemeDetailParts on AccountingScheme {
    id
    displayName
    currency {
        id
        isoCode
        displayName
    }
}

fragment AccountingSchemeListParts on AccountingScheme {
    id
    displayName
    currency {
        id
        isoCode
        displayName
    }
}
