fragment CustomerGroupDetailParts on CustomerGroup {
    id
    displayName
    customers {
        ...CustomerListParts
    }
    customerPriceLists {
        ...CustomerPriceListParts
    }
}

fragment CustomerGroupListParts on CustomerGroup {
    id
    displayName
}
