fragment CustomerDetailParts on Customer {
    id
    legalName
    displayName
    vatNumber
    invoicingEmail
    legalAddress {
        ...AddressListParts
    }
    address {
        ...AddressListParts
    }
    note
}
