fragment FactoringProviderDetailParts on FactoringProvider {
            id
            displayName
            legalName
            contact
            bankAccount {
                ...BankAccountListParts
            }
}
