fragment OrganizationDetailParts on Organization {
            id
            displayName
            legalAddress {
                ...AddressListParts
            }
            legalName
            registration
            contact
            idNumber
            vatNumber
            bankAccount {
                ...BankAccountListParts
            }
            accountingScheme {
                id
            }
}
