import {
  AccountingSchemeService,
  AccountingSchemeServiceKey,
  AccountService,
  AccountServiceKey,
  AddressService,
  AddressServiceKey,
  BankAccountService,
  BankAccountServiceKey,
  BankService,
  BankServiceKey,
  CalendarActivityService,
  CalendarActivityServiceKey,
  CountryService,
  CountryServiceKey,
  CurrencyRateService,
  CurrencyRateServiceKey,
  CurrencyService,
  CurrencyServiceKey,
  CustomerGroupService,
  CustomerGroupServiceKey, CustomerOrderService, CustomerOrderServiceKey,
  CustomerPriceListService,
  CustomerPriceListServiceKey,
  CustomerProductPriceService,
  CustomerProductPriceServiceKey,
  CustomerService,
  CustomerServiceKey, FifoCostsOfGoodsSoldService, FifoCostsOfGoodsSoldServiceKey,
  Injector,
  LanguagesService,
  LanguagesServiceKey,
  LeadService,
  LeadServiceKey,
  OrganizationService,
  OrganizationServiceKey,
  ProductIssueLineService,
  ProductIssueLineServiceKey,
  ProductIssueService,
  ProductIssueServiceKey,
  ProductQuantityOnHandService,
  ProductQuantityOnHandServiceKey,
  ProductReceiptLineService,
  ProductReceiptLineServiceKey,
  ProductReceiptService,
  ProductReceiptServiceKey,
  ProductService,
  ProductServiceKey,
  ProspectService,
  ProspectServiceKey,
  RecurringSalesInvoiceLineService,
  RecurringSalesInvoiceLineServiceKey,
  RecurringSalesInvoiceService,
  RecurringSalesInvoiceServiceKey,
  SalesInvoiceLineService,
  SalesInvoiceLineServiceKey,
  SalesInvoiceService,
  SalesInvoiceServiceKey,
  SalesInvoiceVatService,
  SalesInvoiceVatServiceKey,
  SuspectService,
  SuspectServiceKey,
  TaskService,
  TaskServiceKey,
  TaxService,
  TaxServiceKey,
  TranslationService,
  TranslationServiceKey,
  UserService,
  UserServiceKey,
  UserToOrganizationService,
  UserToOrganizationServiceKey,
  WarehouseService,
  WarehouseServiceKey
} from '@erpjs/model';
import { Inject, Injectable } from '@nestjs/common';
import { DocumentNumberingService, ModelModule, ReportsService } from '@erpjs/data';

@Injectable()
export class InjectorImplementation implements Injector {
  public readonly documentNumberingServiceModel = new DocumentNumberingService();
  public readonly reportsServiceModel;

  constructor(
    @Inject(AddressServiceKey) public readonly addressService: AddressService,
    @Inject(BankAccountServiceKey) public readonly bankAccountService: BankAccountService,
    @Inject(BankServiceKey) public readonly bankService: BankService,
    @Inject(CountryServiceKey) public readonly countryService: CountryService,
    @Inject(CustomerServiceKey) public readonly customerService: CustomerService,
    @Inject(OrganizationServiceKey) public readonly organizationService: OrganizationService,
    @Inject(CurrencyServiceKey) public readonly currencyService: CurrencyService,
    @Inject(AccountingSchemeServiceKey) public readonly accountingSchemeService: AccountingSchemeService,
    @Inject(SalesInvoiceServiceKey) public readonly salesInvoiceService: SalesInvoiceService,
    @Inject(SalesInvoiceLineServiceKey) public readonly salesInvoiceLineService: SalesInvoiceLineService,
    @Inject(TaxServiceKey) public readonly taxService: TaxService,
    @Inject(SalesInvoiceVatServiceKey) public readonly salesInvoiceVatService: SalesInvoiceVatService,
    @Inject(UserServiceKey) public readonly userService: UserService,
    @Inject(UserToOrganizationServiceKey) public readonly userToOrganizationService: UserToOrganizationService,
    @Inject(TaskServiceKey) public readonly taskService: TaskService,
    @Inject(CalendarActivityServiceKey) public readonly calendarActivityService: CalendarActivityService,
    @Inject(LeadServiceKey) public readonly leadService: LeadService,
    @Inject(SuspectServiceKey) public readonly suspectService: SuspectService,
    @Inject(ProspectServiceKey) public readonly prospectService: ProspectService,
    @Inject(ProductServiceKey) public readonly productService: ProductService,
    @Inject(CurrencyRateServiceKey) public readonly currencyRateService: CurrencyRateService,
    @Inject(RecurringSalesInvoiceServiceKey) public readonly recurringSalesInvoiceService: RecurringSalesInvoiceService,
    @Inject(RecurringSalesInvoiceLineServiceKey)
    public readonly recurringSalesInvoiceLineService: RecurringSalesInvoiceLineService,
    @Inject(AccountServiceKey) public readonly accountService: AccountService,
    @Inject(CustomerGroupServiceKey) public readonly customerGroupService: CustomerGroupService,
    @Inject(CustomerPriceListServiceKey) public readonly customerPriceListService: CustomerPriceListService,
    @Inject(CustomerProductPriceServiceKey) public readonly customerProductPriceService : CustomerProductPriceService,
    @Inject(TranslationServiceKey) public readonly translationService: TranslationService,
    @Inject(LanguagesServiceKey) public readonly languagesService: LanguagesService,
    @Inject(ProductQuantityOnHandServiceKey) public readonly productQuantityOnHandService: ProductQuantityOnHandService,
    @Inject(ProductReceiptLineServiceKey) public readonly productReceiptLineService: ProductReceiptLineService,
    @Inject(ProductReceiptServiceKey) public readonly productReceiptService: ProductReceiptService,
    @Inject(WarehouseServiceKey) public readonly warehouseService: WarehouseService,
    @Inject(ProductIssueLineServiceKey) public readonly productIssueLineService: ProductIssueLineService,
    @Inject(ProductIssueServiceKey) public readonly productIssueService: ProductIssueService,
    @Inject(FifoCostsOfGoodsSoldServiceKey) public readonly fifoCostsOfGoodsSoldService: FifoCostsOfGoodsSoldService,
    @Inject(CustomerOrderServiceKey) public readonly customerOrderService: CustomerOrderService,
  ) {
    ModelModule.setInjector(this);
    this.reportsServiceModel= new ReportsService(translationService);
  }
}
