mutation SaveAccountingScheme($id: Int, $displayName: String!, $currencyId: Int!) {
    saveAccountingScheme(
        args: { id: $id, displayName: $displayName, currencyId: $currencyId }
    ) {
        id
    }
}
