fragment CustomerDetailParts on Customer {
    id
    legalName
    displayName
    vatNumber
    idNumber
    invoicingEmail
    legalAddress {
        ...AddressListParts
    }
    address {
        ...AddressListParts
    }
    note
    customerGroup {
        ...CustomerGroupDetailParts
    }
    www
    publicNote
}

fragment CustomerListParts on Customer {
    id
    legalName
    displayName
    vatNumber
    invoicingEmail
    legalAddress {
        ...AddressListParts
    }
    address {
        ...AddressListParts
    }
    note
}
