fragment FactoringProviderDetailParts on FactoringProvider {
            id
            displayName
            legalName
            contact
            bankAccount {
                ...BankAccountListParts
            }
}

fragment FactoringProviderListParts on FactoringProvider {
    contact
    displayName
    id
    legalName
}
