fragment ProductDetailParts on Product {
    id
    displayName
    sku
    defaultUoM {
        ...UnitOfMeasurementDetailParts
    }
}

fragment ProductListParts on Product {
    id
    sku
    displayName
}
