query SalesInvoiceById($id: Int!) {
    salesInvoice(id: $id) {
        ...SalesInvoiceDetailParts
    }
}

mutation DuplicateSalesInvoice($id: Int!) {
    duplicateSalesInvoice(id: $id) {
        id
    }
}
