mutation SaveFactoringProvider(
    $id: Int
    $displayName: String!
    $contact: String!
    $legalName: String!
    $newBankAccount: BankAccountSaveArgs!
) { saveFactoringProvider( args :
{
    id: $id
    displayName: $displayName
    contact: $contact
    legalName: $legalName
    newBankAccount: $newBankAccount
}

) { id } }
