mutation CreateSalesInvoice(
    $id: Int
    $currencyIsoCode: String!
    $customerId:  Int!
    $issuedOn:  Date!
    $lines: [SalesInvoiceLineSaveArgs!]!,
    $organizationId:  Int!
    $paymentTermInDays: Int!
    $transactionDate:  Date!
) { createSalesInvoice( args :
{
    id: $id
    currencyIsoCode: $currencyIsoCode
    customerId: $customerId
    issuedOn: $issuedOn
    lines: $lines,
    organizationId: $organizationId
    paymentTermInDays: $paymentTermInDays
    transactionDate: $transactionDate
}

) { id } }
