mutation SaveOrganization(
    $id: Int
    $displayName: String!
    $accountingSchemeId: Int!
    $contact: String!
    $idNumber: String!
    $legalAddress: AddressSaveArgs!
    $legalName: String!
    $newBankAccount: BankAccountSaveArgs!
    $registration: String!
    $vatNumber: String
    $currentInvoiceDocumentNumber: Float!
) { saveOrganization( args :
{
    id: $id
    displayName: $displayName
    accountingSchemeId: $accountingSchemeId
    contact: $contact
    idNumber: $idNumber
    legalAddress: $legalAddress
    legalName: $legalName
    newBankAccount: $newBankAccount
    registration: $registration
    vatNumber: $vatNumber
    currentInvoiceDocumentNumber: $currentInvoiceDocumentNumber
}

) { id } }
