mutation CreateMonthlyInvoice(
    $totalHours: Float!
    $dailyRate: Float!
    $organizationDivider: [IdAndNumber!]!
    $year: Int!
    $month: Int!
    $day: Int!
    $eurToCzkRate: Float!
    $narration: String!
) {
    createMonthlyInvoice(
        args: {
            totalHours: $totalHours
            dailyRate: $dailyRate
            organizationDivider: $organizationDivider
            year: $year
            month: $month
            day: $day
            eurToCzkRate: $eurToCzkRate
            narration: $narration
        }
    ) {
        id
    }
}
